package-lock.json

addresses:
- #59 (CVE-2021-23337)
- #60 (CVE-2020-28500)
- #61 (CVE-2020-28498)
- #62 (CVE-2021-27515)
- #66 (CVE-2021-23364)

Release 4.0.3 - dependency update

---

LICENSE.txt
installed-versions.json
package-lock.json

- Update dependencies
- Update copyright year in LICENSE file
---
This is just some minor updates. I was trying to update a different sub-dependency, without success, but figured I'd go ahead and release what I did update.

Release 5.0.2

---

LICENSE.txt

Release 5.0.3

---

installed-versions.json
package-lock.json

- Update npm dependencies, including some vulnerable packages

Update npm dependencies

---

LICENSE.txt

- Update npm dependencies
- Update vulnerable dependencies

Release 5.0.4

---

package-lock.json
vue.config.js

- Error due to breaking change introduced in <https://github.com/silinternational/idp-profile-ui/pull/91> by update  to @vue/cli-service": "^5.0.8"

fix broken dev environment

---

package-lock.json
package.json

add "engines" to package.json and run npm install

specify node version

---

package-lock.json
src/2sv/Change.vue
src/2sv/codes/Intro.vue
src/2sv/key/Touch.vue
src/2sv/routes.js
src/global/mfa.js
src/locales/en.json
src/locales/es.json
src/locales/fr.json
src/locales/ko.json
src/profile/Index.vue
src/profile/MfaCardLabel.vue
src/profile/MfaCardRemove.vue
src/profile/ProfileProgress.vue
src/profile/SecurityKeyCard.vue

This picks up where https://github.com/silinternational/idp-profile-ui/pull/105 left off, which I closed without merging.
~~We are still trying to get 'change' and 'remove' endpoints working properly.~~
Updated now has created dates and editing labels works even when only 1 key!

Support multiple keys and use new webauthn endpoints

---

src/global/mfa.js
src/profile/SecurityKeyCard.vue

- hide last used when summary card
- del console.log/todo

hide last used date when summary

---

.gitignore
Makefile
docker-compose.yml
dynamorestart/Dockerfile
dynamorestart/DynamoRestart.php
dynamorestart/composer.json
dynamorestart/composer.lock
dynamorestart/restart.php
serverless-mfa-api/Dockerfile

I borrowed this from idp-id-broker and tested it successfully on my machine.
This is so you don't need to connect with our actual AWS lambda and dynamodb to test it locally.

test mfa locally with dynamodb and serverless-mfa-api-go containers

---

installed-versions.json
package-lock.json
src/profile/BackupCodeCard.vue
src/profile/MfaCardRemove.vue
src/profile/TotpCard.vue

Cors calls were dying with `undefined` as the mfa id and webauthn id

Fix remove non webauthn

---

src/2sv/key/Insert.vue
src/2sv/key/Touch.vue
src/global/mfa.js
src/locales/en.json
src/locales/es.json

- user adds a usb security key name before touch.vue
Needs translations!
If continue is clicked without input
if a duplicate name is entered
After inserting the key the input appears and autofocuses

allow user to name usb key when adding

---

dynamorestart/composer.lock
src/locales/en.json
src/locales/fr.json
src/password/ForgotEmailSent.vue

In case you need them for local development, the always-passing recaptcha keys can be found here:
https://developers.google.com/recaptcha/docs/faq#id-like-to-run-automated-tests-with-recaptcha.-what-should-i-do

IDP-7 Accentuate alternate/backup email sending option

---

src/password/Confirm.vue
src/password/Create.vue

add a show password button

---

package-lock.json
package.json
src/profile/Index.vue

- updated to vue 2.7
- changed to composable api in profile/index.vue
- vue-template-compiler as part of migration
- added vue-demi as part of migration
Migration guide
https://v2.vuejs.org/v2/guide/migration-vue-2-7.html

Update vue to 2.7

---

.env.dist
.gitignore
.prettierignore
.prettierrc
.vscode/settings.json
vue.config.js

- add VUE_ALLOWED_HOSTS env
- add prettierrc
- add prettierignore
- add .vscode/settings

add VUE_ALLOWED_HOSTS env and pretter config

---

.env.dist

- proxy container was failing to start

missing env caused proxy to fail

---

dynamorestart/composer.lock
installed-versions.json
package-lock.json

[IDP-888](https://itse.youtrack.cloud/issue/IDP-888/clear-idp-profile-ui-CVE-list-on-Deepfactor)
note: last time we updated I think it was just with `npm update` so the change is from axios 1.6 not .27

ran make depsupdate and make IDP-888

---

.github/workflows/test.yml
dynamorestart/composer.lock
installed-versions.json
package-lock.json

- updated deps with `make depsupdate` and `make`

Release 5.3.2

---

src/main.js

[ITSE-611](https://itse.youtrack.cloud/issue/ITSE-611)

fix typos in Sentry config ITSE-611

---

src/profile/ProfileWizard.vue
src/profile/steps.js

[IDP-952](https://itse.youtrack.cloud/issue/IDP-952)

fix missing previous steps IDP-952

---

src/password/Create.vue

[IDP-1094](https://itse.youtrack.cloud/issue/IDP-1094)

password validation on-input

---

package-lock.json
package.json
src/App.vue
src/global/Loading.vue
src/global/mfa.js
src/plugins/api.js

install prettier so make format will work for those w/o extension
note: I didn't want to figure out how to configure es-lint and all the plugins to enforce prettier until we update this repo to vue 3

formatting with prettier

---

src/main.js
src/password/VerifyReset.vue

[ITSE-1396](https://itse.youtrack.cloud/issue/ITSE-1396)

ITSE-1396  silence sentry locally and use hostname as environment

---

installed-versions.json
package-lock.json
package.json
src/2sv/key/Insert.vue
src/2sv/key/Intro.vue
src/2sv/key/Touch.vue
src/2sv/smartphone/DownloadApp.vue
src/App.vue
src/global/PageNotFound.vue

- fix some images not loading [ref](https://vite.dev/guide/assets)

fix inconsistent image loading

---

.gitignore
installed-versions.json
package-lock.json
package.json
src/2sv/key/Insert.vue
src/2sv/key/Intro.vue
src/2sv/key/Touch.vue
src/2sv/smartphone/DownloadApp.vue
src/App.vue
src/global/PageNotFound.vue

Release 7.0.1 Fix image loading

---

.gitignore
dynamorestart/composer.lock
installed-versions.json
package-lock.json
package.json
vite.config.mjs

[ITSE-1565](https://itse.youtrack.cloud/issue/ITSE-1565) Unminify senty stacktrace in ui repos
---
- add @sentry/vite-plugin to unminify with source maps (will need to add the env to idps)
- ran `make depsupdate`

allow sentry to unminify with source maps

---

.env.dist
Makefile
README.md
docker-compose.yml
serverless-mfa-api/Dockerfile

- Added documentation details for development
- Added `--build` flag to docker compose to ensure the local images are built each time you start development.
- Use explicit tags on images pulled by docker compose

fixes and helps for development config

---

.env.dist
vite.config.mjs

[ITSE-1565](https://itse.youtrack.cloud/issue/ITSE-1565) Unminify senty stacktrace in ui repos
---
- add VITE_PROJECT_NAME for sentry plugin
Question: do any organizations manage their own sentry reporting? If so we might need another env for that.

add VITE_PROJECT_NAME for sentry plugin

---

docker-compose.yml
package-lock.json
package.json

[ITSE-1565](https://itse.youtrack.cloud/issue/ITSE-1565) Unminify senty stacktrace in ui repos
---
- [add VITE_PROJECT_NAME for sentry plugin](https://github.com/silinternational/idp-profile-ui/commit/e29fb0fdabfed25dccea82d9a519beee84ec6f1b)

Release - add env for project name for sentry plugin

---

installed-versions.json
package-lock.json
package.json
src/profile/MfaCardLabel.vue
src/profile/SecurityKeyCard.vue
src/profile/TotpCard.vue

- [IDP-24](https://itse.youtrack.cloud/issue/IDP-24) Remove Smartphone check
---
- Add ability to edit totp label

Release 7.2.0 - Add ability to edit totp label

---

installed-versions.json
package-lock.json
package.json
src/2sv/smartphone/Intro.vue
src/profile/BackupCodeCard.vue
src/profile/Index.vue
src/profile/SecurityKeyCard.vue
src/profile/TotpCard.vue
src/profile/steps.js

[IDP-547](https://itse.youtrack.cloud/issue/IDP-547) When I added Printable Code, it then asked if I wanted to add a USB key (even though I had three by that time in the workflow.)
- Fix wrong directive typo
- Fix prop typo
- Fix asking for a key when I already have one

Release - Fix wrong directive and prop typo

---

.env.dist
.github/pull_request_template.md
.github/workflows/test.yml
installed-versions.json
package-lock.json
package.json
vite.config.mjs

- remove version from package.json
- fix env vars for Sentry in vite.config as cloudflare pages doesn't support `process.env`

fix env vars in vite.config and remove version from package.json

---

dynamorestart/composer.lock
installed-versions.json
package-lock.json
package.json
src/2sv/smartphone/DownloadApp.vue
src/App.vue
src/main.js

[IDP-1270](https://itse.youtrack.cloud/issue/IDP-1270) Fix idp-profile-ui sonar warnings
- Fix sanitize bypassing

fix a few sonar warnings about bypassing sanitizing

---

package-lock.json
src/2sv/smartphone/Intro.vue

- fixed a broken link introduced in [Fix asking to add a USB key when I already have one](https://github.com/silinternational/idp-profile-ui/releases/tag/7.2.1)

link was broken

---

Makefile
installed-versions.json
package-lock.json
src/2sv/codes/New.vue
src/App.vue
src/main.js
src/password/Confirm.vue
src/password/Create.vue
src/password/Forgot.vue
src/profile/Index.vue
src/profile/PasswordRecoveryCard.vue

- Fix not showing error on password/reset (wrong username or Do not disclose is on)
- fix printing code styles
- fix resend email button styles
- fix password is retained on password/confirm
- fix missing padding toolbar and other places

Fix vue3 bugs

---

.github/workflows/test.yml
src/2sv/Intro.vue
src/2sv/key/Intro.vue
src/global/mfa.js
src/help/HelpButton.vue
src/locales/en.json
src/locales/es.json
src/locales/fr.json
src/locales/ko.json
src/main.js
src/profile/steps.js

[IDP-547](https://itse.youtrack.cloud/issue/IDP-547) When I added Printable Code, it then asked if I wanted to add a USB key (even though I had three by that time in the workflow.)
---
- break 2sv step into individual steps
- skip security key step if one exists
- skip 2sv intro if not needed
- unused `install` part of test script
- conditionally showing help button

Add 2sv steps and skip intro and security key if not needed

---

installed-versions.json
package-lock.json

- updates Vite which addresses a security [alert](https://github.com/silinternational/idp-profile-ui/security/dependabot/65)

run make depsupdate

---

src/2sv/Intro.vue
src/2sv/key/Confirmed.vue
src/2sv/smartphone/CodeVerified.vue
src/2sv/smartphone/Intro.vue
src/main.js
src/password/CompleteReset.vue

[IDP-547](https://itse.youtrack.cloud/issue/IDP-547) When I added Printable Code, it then asked if I wanted to add a USB key (even though I had three by that time in the workflow.)
---
- fix skipping security key step if mfa < 3
- fix not marking steps complete
- fix id of undefined error if steps not initialized for 2sv intro

Fix profile bugs

---

src/global/mfa.js
src/plugins/vuetify.js
src/profile/ProfileWizard.vue

[IDP-1407](https://itse.youtrack.cloud/issue/IDP-1407) IDP Profile not full width after Vue upgrade
[IDP-1406](https://itse.youtrack.cloud/issue/IDP-1406) Removing any MFA does not refresh UI
---
- fix  IDP Profile not full width after Vue upgrade
- fix Removing any MFA does not refresh UI

Fix remove mfa bug and breakpoints

---

docker-compose.yml
installed-versions.json
package-lock.json
package.json

- Updated API Docker image to the latest minor versions of version 7: `silintl/idp-pw-api:7`
- Upgraded vue-i18n from v9 to v10 to address security vulnerability 
-   https://github.com/silinternational/idp-profile-ui/security/dependabot/67
- Bumped various dependencies to their latest minor versions
---

Dependency Updates

---

docker-compose.yml
src/locales/en.json

- fix password recovery message ([IDP-1467](https://itse.youtrack.cloud/issue/IDP-1467))
- Changed APP_ENV for idp-pw-api to `dev` so errors render to the web page for easier troubleshooting.
- Fixed spelling error in verify recovery message
- Removed unnecessary variables in api container definition. ([IDP-1476](https://itse.youtrack.cloud/issue/IDP-1476)) (Requires idp-pw-api https://github.com/silinternational/idp-pw-api/pull/316)

Release 7.2.15 -- fixed spelling error

---

Dockerfile
docker-compose.yml
dynamorestart/composer.lock
installed-versions.json
package-lock.json
package.json

[ITSE-1917](https://support.gtis.sil.org/issue/ITSE-1917) Update node from EOL 18
---
- use node 22 (will need to update envs for all instances)

use node 22
